## The dataset is compiled from the 1994 Census database and contains income data.
### Data Information:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Perform data analysis using Pandas by completing the given tasks.
####

In [1]:
import pandas as pd

In [2]:
# loading the dataset
data = pd.read_csv("./data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Calculate how many men and women (attribute *sex*) are represented in this dataset.**

In [3]:
# your code
data['sex'].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. What is the average age of men (attribute *age*) across the entire dataset?**

In [23]:
# your code
data[data['sex'] == 'Male'].loc[:, 'age'].mean()

39.43354749885268

**3. What is the proportion of United States citizens (*native-country* attribute)?**

In [24]:
# your code
len(data[data['native-country']=='United-States']) / len(data)

0.895857006848684

**4-5. Calculate the mean and standard deviation of the age of those who earn more than 50K per year (the *salary* attribute) and those who earn less than 50K per year**

In [25]:
# your code
std_mean = data.groupby('salary')['age'].agg(['mean', 'std'])

std_mean

             mean        std
salary
<=50K   36.783738  14.020088
>50K    44.249841  10.519028

**6. Is it true that people who earn more than 50k have at least a higher education? (*education indicator – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters or Doctorate*)**

In [4]:
# your code
list = ['Bachelors', 'Prof-school', 'Assoc-acdm', 'Assoc-voc', 'Masters', 'Doctorate']

sumpost50 = data[(data['salary']=='>50K') & (data['education'].isin(list))].loc[:, 'education'].value_counts().sum()
sumpre50 = data[(data['salary']=='<=50K') & (data['education'].isin(list))].loc[:, 'education'].value_counts().sum()

sumpost50 > sumpre50

False

**7. Find age statistics for each race (*race* attribute) and each gender. Use *groupby* and *describe*. Find the maximum age of males of the *Asian-Pac-Islander* race.**

In [27]:
# your code
race_gender = data.groupby(['race', 'sex']).describe()
asian_males_max = data[(data['sex']=='Male') & (data['race']=='Asian-Pac-Islander')].describe().loc[['max']]

race_gender, asian_males_max

(                               age                                          \
                              count       mean        std   min   25%   50%
 race               sex
 Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                    Male      192.0  37.208333  12.049563  17.0  28.0  35.0
 Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                    Male      693.0  39.073593  12.883944  18.0  29.0  37.0
 Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                    Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
 Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                    Male      162.0  34.654321  11.355531  17.0  26.0  32.0
 White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                    Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                                          fnlwgt                 ...  \
                              75%   max    count           mean  ...
 race               sex                                          ...
 Amer-Indian-Eskimo Female  46.00  80.0    119.0  112950.731092  ...
                    Male    45.00  82.0    192.0  125715.364583  ...
 Asian-Pac-Islander Female  43.75  75.0    346.0  147452.075145  ...
                    Male    46.00  90.0    693.0  166175.865801  ...
 Black              Female  46.00  90.0   1555.0  212971.387781  ...
                    Male    46.00  90.0   1569.0  242920.644997  ...
 Other              Female  39.00  74.0    109.0  172519.642202  ...
                    Male    42.00  77.0    162.0  213679.104938  ...
 White              Female  46.00  90.0   8642.0  183549.966906  ...
                    Male    49.00  90.0  19174.0  188987.386148  ...

                           capital-loss         hours-per-week             \
                                    75%     max          count       mean
 race               sex
 Amer-Indian-Eskimo Female          0.0  1721.0          119.0  36.579832
                    Male            0.0  1980.0          192.0  42.197917
 Asian-Pac-Islander Female          0.0  2258.0          346.0  37.439306
                    Male            0.0  2457.0          693.0  41.468975
 Black              Female          0.0  4356.0         1555.0  36.834084
                    Male            0.0  2824.0         1569.0  39.997451
 Other              Female          0.0  1740.0          109.0  35.926606
                    Male            0.0  2179.0          162.0  41.851852
 White              Female          0.0  4356.0         8642.0  36.296691
                    Male            0.0  3770.0        19174.0  42.668822


                                  std  min   25%   50%   75%   max
 race               sex
 Amer-Indian-Eskimo Female  11.046509  4.0  35.0  40.0  40.0  84.0
                    Male    11.596280  3.0  40.0  40.0  45.0  84.0
 Asian-Pac-Islander Female  12.479459  1.0  35.0  40.0  40.0  99.0
                    Male    12.387563  1.0  40.0  40.0  45.0  99.0
 Black              Female   9.419960  2.0  35.0  40.0  40.0  99.0
                    Male    10.909413  1.0  40.0  40.0  40.0  99.0
 Other              Female  10.300761  6.0  30.0  40.0  40.0  65.0
                    Male    11.084779  5.0  40.0  40.0  40.0  98.0
 White              Female  12.190951  1.0  30.0  40.0  40.0  99.0
                    Male    12.194633  1.0  40.0  40.0  50.0  99.0

 [10 rows x 48 columns],
       age    fnlwgt  education-num  capital-gain  capital-loss  hours-per-week
 max  90.0  506329.0           16.0       99999.0        2457.0            99.0)

**8. Among whom is the proportion of high-earning individuals (>50K) higher: married or single men (*marital-status* indicator)? We consider those whose *marital-status* begins with *Married* (Married-civ-spouse, Married-spouse-absent, or Married-AF-spouse) to be married; the rest are considered single.**

In [28]:
# your code
per_married = len(data[(data['marital-status'].str.startswith('Married')) & (data['salary']=='>50K') & (data['sex']=='Male')]) / len(data[(data['salary']=='>50K') & (data['sex']=='Male')])
per_not_married = len(data[~(data['marital-status'].str.startswith('Married')) & (data['salary']=='>50K')  & (data['sex']=='Male')]) / len(data[(data['salary']=='>50K') & (data['sex']=='Male')])

per_married, per_not_married

(0.8953767637346143, 0.10462323626538576)

**9. What is the maximum number of hours a person works per week (hours-per-week indicator)? How many people work that many hours, and what percentage of them earn a lot?**

In [29]:
# your code
count_max = len(data[data['hours-per-week']==data.loc[:, 'hours-per-week'].max()])
per_earn = len(data[(data['hours-per-week']==data.loc[:, 'hours-per-week'].max()) & (data['salary']=='>50K')]) / len(data[data['hours-per-week']==data.loc[:, 'hours-per-week'].max()])

count_max, per_earn

(85, 0.29411764705882354)

**10. Calculate the average working hours (*hours-per-week*) of low and high earners (*salary*) for each country (*native-country*).**

In [30]:
# your code
earners = data.groupby(['native-country', 'salary'])['hours-per-week'].mean()
earners

native-country  salary
?               <=50K     40.164760
                >50K      45.547945
Cambodia        <=50K     41.416667
                >50K      40.000000
Canada          <=50K     37.914634
                            ...
United-States   >50K      45.505369
Vietnam         <=50K     37.193548
                >50K      39.200000
Yugoslavia      <=50K     41.600000
                >50K      49.500000
Name: hours-per-week, Length: 82, dtype: float64

**11.Group people into age groups *young*, *adult*, *retiree*, where:**
* *young* corresponds to 16-35 years old
* *adult* - 35-70 years old
* *retiree* - 70-100 years old

**Enter the name of the appropriate age group for each person in the new AgeGroup column.**

In [31]:
# your code
# data['AgeGroup'] = ['young' if x < 35 else 'adult' if x >= 35 and x < 70 else 'retiree' for x in data['age']]
data['AgeGroup'] = pd.cut(data['age'], bins=[16, 35, 70, 100], labels=['young', 'adult', 'retiree'], right=False)
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,adult
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,adult
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,adult
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,adult
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,young

**12-13. Determine the number of people earning >50K in each age group (AgeGroup column), and also output the name of the age group in which people most often earn more than 50K (>50K)**

In [32]:
# your code
nmb_earning = data[data['salary']=='>50K'].groupby('AgeGroup').size()
max_group = (data[data['salary']=='>50K'].groupby('AgeGroup').size() / data.groupby('AgeGroup').size()).idxmax()

nmb_earning, max_group

(AgeGroup
 young      1488
 adult      6240
 retiree     113
 dtype: int64,
 'adult')

**14. Group people by employment type (the occupation column) and determine the number of people in each group. Then write a filter function, filter_func, that will return only those groups in which the average age (the age column) is 40 or less and in which all employees work more than 5 hours per week (the hours-per-week column).**

In [33]:
# your code
dt_group = data.groupby('occupation').size()
def filter_func(data, age, hours):
    dt = data.groupby('occupation').filter(lambda x: ((x['age'].mean() <= age) & (x['hours-per-week'] > hours)).all())
    return dt

dt = filter_func(data, 40, 5)
dt_group, dt

(occupation
 ?                    1843
 Adm-clerical         3770
 Armed-Forces            9
 Craft-repair         4099
 Exec-managerial      4066
 Farming-fishing       994
 Handlers-cleaners    1370
 Machine-op-inspct    2002
 Other-service        3295
 Priv-house-serv       149
 Prof-specialty       4140
 Protective-serv       649
 Sales                3650
 Tech-support          928
 Transport-moving     1597
 dtype: int64,
        age    workclass  fnlwgt     education  education-num  \
 442     24  Federal-gov  191073       HS-grad              9
 1300    29  Federal-gov  301010  Some-college             10
 14613   39  Federal-gov  227597       HS-grad              9
 16111   24  Federal-gov  287988     Bachelors             13
 18034   34  Federal-gov  172716          12th              8
 18644   23  Federal-gov  163870  Some-college             10
 18769   30  Federal-gov   76313       HS-grad              9
 25799   46  Federal-gov  344415       Masters             14
 32316   23  Federal-gov  173851       HS-grad              9

            marital-status    occupation    relationship                race  \
 442         Never-married  Armed-Forces       Own-child               White
 1300        Never-married  Armed-Forces   Not-in-family               Black
 14613       Never-married  Armed-Forces   Not-in-family               White
 16111       Never-married  Armed-Forces   Not-in-family               White
 18034  Married-civ-spouse  Armed-Forces         Husband               White
 18644       Never-married  Armed-Forces  Other-relative               White
 18769  Married-civ-spouse  Armed-Forces  Other-relative  Amer-Indian-Eskimo
 25799  Married-civ-spouse  Armed-Forces         Husband               White
 32316       Never-married  Armed-Forces   Not-in-family               White

         sex  capital-gain  capital-loss  hours-per-week native-country salary  \
 442    Male             0             0              40  United-States  <=50K
 1300   Male             0             0              60  United-States  <=50K
 14613  Male             0             0              50  United-States  <=50K
 16111  Male             0             0              40  United-States  <=50K
 18034  Male             0             0              40  United-States  <=50K
 18644  Male             0             0              40  United-States  <=50K
 18769  Male             0             0              48  United-States  <=50K
 25799  Male             0          1887              40  United-States   >50K
 32316  Male             0             0               8  United-States  <=50K

       AgeGroup
 442      young
 1300     young
 14613    adult
 16111    young
 18034    young
 18644    young
 18769    young
 25799    adult
 32316    young  )